# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PGE', '0003_auto_20170628_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='priority',
        ),
        migrations.AddField(
            model_name='priority',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGE.Role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='priority',
            field=models.ManyToManyField(to='PGE.Priority'),
        ),
    ]
