# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PGE', '0004_auto_20170628_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='roles',
        ),
    ]
