# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PGE', '0005_remove_employee_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ManyToManyField(to='PGE.Employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGE.Role')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 7, 12)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2017, 8, 11)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 7, 12)),
        ),
        migrations.AddField(
            model_name='project',
            name='selections',
            field=models.ManyToManyField(to='PGE.Selection'),
        ),
    ]
